### ISSUE TITLE
How do I solve it?

### ISSUE THREAD

**Issue by EDGCnb** [flybywiresim/aircraft#8776]
### Aircraft Version

Stable

### Build info

```json
Error: FragmenterError(Unknown): connect ETIMEDOUT 2400:52e0:1a01::985:1:443
    at oi.createFromError (C:\Users\m1382\AppData\Local\Programs\fbw-installer\resources\app.asar\webpack\main\main.js:2:234616)
    at Yo.<anonymous> (C:\Users\m1382\AppData\Local\Programs\fbw-installer\resources\app.asar\webpack\main\main.js:2:290375)
    at Generator.throw (<anonymous>)
    at a (C:\Users\m1382\AppData\Local\Programs\fbw-installer\resources\app.asar\webpack\main\main.js:2:13641)
```

### Describe the bug

I want to download your A32nx aircraft mod, but it's reporting an error.

### Expected behavior

I want to successfully download your mod.

### Steps to reproduce

1.Click to install directly.
2.An error occurred.

**Comment by Pruznak** [comment]
You should post this on FBW discord in #installer-support

**Comment by EDGCnb** [comment]
I don't find #installer-support，where?

**Comment by ImenesFBW** [comment]
[#installer-support](https://discord.com/channels/738864299392630914/1065394439608078336)

I am closing this since it is not related to the aircraft repo.
