### ISSUE TITLE
Corupt Download

### ISSUE THREAD

**Issue by GunterHar** [flybywiresim/aircraft#9036]
### Aircraft Version

Stable

### Build info

```json
Error: FragmenterError(Unknown): invalid central directory file header signature: 0x660002f3
    at FragmenterError.createFromError (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:57257:12)
    at ModuleDecompressor.<anonymous> (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:60326:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:40829:32)
```

### Describe the bug

Error: FragmenterError(Unknown): invalid central directory file header signature: 0x660002f3
    at FragmenterError.createFromError (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:57257:12)
    at ModuleDecompressor.<anonymous> (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:60326:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\User\AppData\Local\Programs\fbw-installer\resources\app.asar\out\main\index.js:40829:32)

### Expected behavior

Error File and not able to update

### Steps to reproduce

Download the update

**Comment by alepouna** [comment]
This is the aircraft repo, please submit the issue to the installer repo after receiving support from our Discord #installer-support channel. https://github.com/flybywiresim/installer.
